models/Agenda.py
# models/agenda.py
from flask_sqlalchemy import SQLAlchemy
from database import db


class Agenda(db.Model):
    __tablename__ = 'agenda'
    id_a = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
    fecha_hora_inicial = db.Column(db.DateTime, nullable=False)
    fecha_hora_final = db.Column(db.DateTime, nullable=False)
    id_doctor = db.Column(db.Integer, db.ForeignKey('usuario.id_u'), nullable=False)
    doctor = db.relationship('Usuario', backref=db.backref('agendas', lazy=True))

    def __init__(self, fecha_hora_inicial, fecha_hora_final, id_doctor):
        self.fecha_hora_inicial = fecha_hora_inicial
        self.fecha_hora_final = fecha_hora_final
        self.id_doctor = id_doctor

controllers/admin_controller.py
# controllers/admin_controller.py
from flask import Blueprint, jsonify, render_template, request, redirect, session, flash, url_for
from models import Usuario, ProductoAlmacenad, Agenda
from database import db
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask import current_app

# Luego, en tu código, puedes acceder a la aplicación actual así:
admin = Blueprint('admin', __name__)
bcrypt = Bcrypt()

##############
@admin.route('/inventario')
def inventario():
    user_id = session.get('user_id')
    tipo_usuario = session.get('tipo_usuario')

    if user_id and tipo_usuario=="admin":
      productos = ProductoAlmacenad.query.all()
      return render_template('inventario.html', productos=productos)
    else:
          flash('Debes iniciar sesión para acceder al dashboard', 'warning')
          return render_template('index.html')
#metodo consultas
@admin.route('/optometras')
def optometras():
    user_id = session.get('user_id')
    tipo_usuario = session.get('tipo_usuario')
    if user_id and tipo_usuario=="admin":
      usuarios = Usuario.query.filter(Usuario.rol.in_(["doctor", "admin"]), Usuario.estado_u == "activo").all()
      return render_template('optometras.html', optometras=usuarios)
    else:
         flash('Debes iniciar sesión para acceder al dashboard', 'warning')
         return render_template('index.html')
######
@admin.route('/registro_doctor', methods=['GET', 'POST'])
def registro_doctor():
    if request.method == 'POST':
        # Verifica si el usuario actual es un administrador
        if session.get('tipo_usuario') == 'admin':
            # Obtener los datos del formulario
          nombre = request.form['nombre']
          apellidos = request.form['apellidos']
          edad = request.form['edad']
          tel = request.form['tel']
          n_documento = request.form['n_documento']
          t_documento = request.form['t_documento']
          email = request.form['email']
          dirrecion = request.form['dirrecion']
          contra = request.form['contra']
          rol = request.form['rol']  # Obtiene el valor del campo de selección de rol


            # Hash de la contraseña
          hashed_password = bcrypt.generate_password_hash(contra).decode('utf-8')

          nuevo_usuario = Usuario(
            nombre=nombre,
            apellidos=apellidos,
            edad=edad,
            tel=tel,
            n_documento=n_documento,
            t_Documento=t_documento,
            email=email,
            dirrecion=dirrecion,
            contra=hashed_password,
            rol=rol  # Asigna el rol según el valor del campo de selección
         )

          db.session.add(nuevo_usuario)
          db.session.commit()

            # Redireccionar a la página de inicio después de registrar el doctor
          return render_template('dashadminaler.html')
        else:
            flash('No tienes permisos para registrar doctores, ni administradores', 'danger')
            return redirect(url_for('index.html'))

    # Si la solicitud es GET, simplemente renderiza el formulario de registro
    return render_template('formregistro_doctor.html')
@admin.route('/editar_doctor/<int:id>', methods=['GET', 'POST'])
def editar_doctor(id):
    # Verifica si el usuario actual es un administrador
    if session.get('tipo_usuario') != 'admin':
        flash('No tienes permisos para editar doctores', 'danger')
        return redirect(url_for('/'))

    # Busca el doctor en la base de datos por su ID
    doctor = Usuario.query.get(id)

    if request.method == 'POST':
        # Obtiene los datos del formulario de edición
        doctor.nombre = request.form['nombre']
        doctor.apellidos = request.form['apellidos']
        doctor.edad = request.form['edad']
        doctor.tel = request.form['tel']
        doctor.n_documento = request.form['n_documento']
        doctor.t_Documento = request.form['t_documento']
        doctor.email = request.form['email']
        doctor.dirrecion = request.form['dirrecion']
        doctor.rol = request.form['rol']
        # Guarda los cambios en la base de datos
        db.session.commit()

        flash('Los cambios se guardaron correctamente', 'success')
        return render_template('dashadminaler.html')

    # Renderiza el formulario de edición con los datos del doctor
    return render_template('editar_doctor.html', doctor=doctor)
@admin.route('/eliminar_doctor/<int:id>', methods=['POST'])
def eliminar_doctor(id):
    # Verifica si el usuario actual es un administrador
    if session.get('tipo_usuario') != 'admin':
        flash('No tienes permisos para eliminar doctores', 'danger')
        return redirect(url_for('main./'))

    # Busca el doctor en la base de datos por su ID
    doctor = Usuario.query.get(id)

    if doctor:
        # Cambia el estado del doctor a "desactivado"
        doctor.estado_u = 'no activo'
        db.session.commit()
        flash('El doctor ha sido desactivado correctamente', 'success')
        return render_template('desacti.html')
    else:
        flash('Doctor no encontrado', 'danger')

    return redirect(url_for('admin.optometras'))
@admin.route('/pacientes')
def pacientes():
    user_id = session.get('user_id')
    tipo_usuario = session.get('tipo_usuario')
    if user_id and tipo_usuario=="admin":
      usuarios = Usuario.query.filter_by(rol="pac").all()

      return render_template('pacientes.html', optometras=usuarios)
    else:
         flash('Debes iniciar sesión para acceder al dashboard', 'warning')
         return render_template('index.html')
@admin.route('/agendas')
def agendas():
    user_id = session.get('user_id')
    tipo_usuario = session.get('tipo_usuario')
     
    if user_id and tipo_usuario == "admin":
        # Realiza una consulta que incluye las agendas con sus IDs y los nombres de los doctores
        agendas = Agenda.query.join(Usuario, Usuario.id_u == Agenda.id_doctor).add_columns(
            Agenda.id_a,  # Agrega el ID de la agenda a la consulta
            Agenda.fecha_hora_inicial, 
            Agenda.fecha_hora_final, 
            Usuario.nombre.label('nombre_doctor'),
            Usuario.apellidos.label('apellidos')
        ).all()
        return render_template('agendas.html', agendas=agendas)
    else:
        flash('Debes iniciar sesión para acceder al dashboard', 'warning')
        return render_template('index.html')

@admin.route('/registro_agenda', methods=['GET', 'POST'])
def registro_agenda():
    if request.method == 'POST':
        if session.get('tipo_usuario') == 'admin':
        # Obtener los datos del formulario
         fecha_inicio = request.form['fecha_inicio']
         fecha_fin = request.form['fecha_fin']
         doctor_id = request.form['doctor']  # Esto captura el ID del doctor seleccionado en el formulario

         # Insertar la nueva agenda en la base de datos (debes tener un modelo de datos para las agendas también)
         nueva_agenda = Agenda(fecha_hora_inicial=fecha_inicio, fecha_hora_final=fecha_fin, id_doctor=doctor_id)
         db.session.add(nueva_agenda)
         db.session.commit()

         return render_template('registroagendaexi.html')
        else:
            flash('No tienes permisos para registrar doctores, ni administradores', 'danger')
            return redirect(url_for('index.html'))

    # Si el método es GET, consulta la lista de doctores y muestra el formulario
    doctores = Usuario.query.filter_by(estado_u='activo', rol='doctor').all()
    return render_template('registro_agenda.html', doctores=doctores)
@admin.route('/edita_agenda/<int:id>', methods=['GET', 'POST'])
def edita_agenda(id):

    agenda = Agenda.query.get(id)

    if request.method == 'POST':
        fecha_inicio = request.form['fecha_inicio']
        fecha_fin = request.form['fecha_fin']
        nuevo_doctor_nombre = request.form['nuevo_doctor']  # Obtén el nuevo nombre del doctor desde el formulario

        # Busca al doctor por nombre en la base de datos
        nuevo_doctor = Usuario.query.filter_by(nombre=nuevo_doctor_nombre, rol='doctor').first()

        if nuevo_doctor:
            # Actualiza los valores de la agenda
            agenda.fecha_hora_inicial = fecha_inicio
            agenda.fecha_hora_final = fecha_fin
            agenda.id_doctor = nuevo_doctor.id_u  # Actualiza el ID del doctor en la agenda

            db.session.commit()

            flash('La agenda se ha actualizado correctamente', 'success')
            return render_template('actuexitag.html')
        else:
            flash('El doctor especificado no existe', 'danger')

    # Consulta la lista de doctores disponibles para llenar el menú desplegable
    doctores = Usuario.query.filter_by(estado_u='activo',rol='doctor').all()

    return render_template('edita_agenda.html', agenda=agenda, doctores=doctores)

    # Lógica para editar información de agendas
    # ...
@admin.route('/eliminar_agenda/<int:id>', methods=['POST'])
def eliminar_agenda(id):
    # Verifica si el usuario actual es un administrador
    if session.get('tipo_usuario') != 'admin':
        flash('No tienes permisos para eliminar agendas', 'danger')
        return redirect(url_for('admin.agendas'))

    # Busca la agenda en la base de datos por su ID
    agenda = Agenda.query.get(id)

    if agenda:
        # Elimina la agenda de la base de datos
        db.session.delete(agenda)
        db.session.commit()
        flash('La agenda ha sido eliminada correctamente', 'success')
        return render_template('eliexitage.html')
    else:
        flash('Agenda no encontrada', 'danger')

    return redirect(url_for('admin.agendas'))

@admin.route('/formulario_modificar/<int:id>', methods=['GET'])
def formulario_modificar(id):

controllers/main_controller.py
# controllers/main_controller.py
from flask import Blueprint, render_template, request, redirect, session, flash, url_for
from flask_bcrypt import Bcrypt
from models import Usuario
from database import db
from flask import current_app

# Luego, en tu código, puedes acceder a la aplicación actual así:
main = Blueprint('main', __name__)
bcrypt = Bcrypt()

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/registro', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        # Obtener los datos del formulario
        nombre = request.form['nombre']
        apellidos = request.form['apellidos']
        edad = request.form['edad']
        tel = request.form['tel']
        n_documento = request.form['n_documento']
        t_documento = request.form['t_documento']
        email = request.form['email']
        dirrecion = request.form['dirrecion']
        contra = request.form['contra']
        hashed_password = bcrypt.generate_password_hash(contra).decode('utf-8')

        nuevo_usuario = Usuario(nombre=nombre, apellidos=apellidos, edad=edad, tel=tel, n_documento=n_documento, t_Documento=t_documento, email=email, dirrecion=dirrecion, contra=hashed_password)
        db.session.add(nuevo_usuario)
        db.session.commit()

        # Redireccionar a la página de inicio después de registrar el usuario
        return render_template('indexalert.html')
    
    # Si la solicitud es GET, simplemente renderiza el formulario de registro
    return render_template('formregistro.html')
@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['username']
        contra = request.form['password']
        user = Usuario.query.filter_by(email=email).first()
        if user:
            # Si la contraseña no está cifrada, verifica sin cifrar
         if user.contra == contra and user.email==email or (user.contra and bcrypt.check_password_hash(user.contra, contra)):
                session['user_id'] = user.id_u
                session['tipo_usuario'] = user.rol
                flash('Inicio de sesión exitoso!', 'success')
                return redirect(url_for('main.dashboard')) 
         return render_template("contramal.html")
    # If the request is GET or the login was unsuccessful, render the login page.
    return render_template("login.html")

@main.route('/logout')
def logout():
    session.pop('user_id', None)
    flash('Has cerrado sesión exitosamente', 'info')
    return render_template('secion.html')
@main.route('/dashboard')
def dashboard():
    user_id = session.get('user_id')
    tipo_usuario = session.get('tipo_usuario')
    if user_id:
        user = Usuario.query.get(user_id),Usuario.query.get(tipo_usuario)
        if tipo_usuario=='admin':
        
          return render_template('PrincipalAdmin.html', user=user)
        elif tipo_usuario=='pac':
             return render_template('PrincipalResidente.html', user=user)
        elif tipo_usuario=='doctor':
            return render_template('PrincipalVigilante.html',user=user)
    else:
     flash('Debes iniciar sesión para acceder al dashboard', 'warning')
     return render_template('index.html')

controllers/paciente_controller.py
# controllers/paciente_controller.py
from flask import Blueprint, render_template, request, redirect, session, flash, url_for
from models import Usuario
from flask_sqlalchemy import SQLAlchemy
from flask import current_app
from database import db  # Importa la instancia de la base de datos

# Luego, en tu código, puedes acceder a la aplicación actual así:
paciente = Blueprint('paciente', __name__)



templates/PrincipalAdmin.html

<html>
        <head>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
            <meta charset="utf-8">
            <style>
       .navbar {
        background: linear-gradient(to right, #2165BF, #4CD73B); /* Combinación de colores azul y verde */
        color: white;
        padding: 15px 30px; /* Aumentar el espacio vertical y horizontal */
        display: flex;
        justify-content: space-between; /* Mover el logo y el botón a los lados */
        align-items: center; /* Centrar verticalmente */
    }

    /* Estilos para el botón "Volver" */
    .volver-button {
        background-color: #2165BF; /* Color azul */
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        margin-right: 10px; /* Espacio a la derecha del botón */
    }

    .volver-button:hover {
        background-color: #5660e9; /* Cambio a verde al hacer hover */
        text-decoration: none;
    }

    /* Estilos para el logo */
    .logo {
        width: 10px; /* Ancho del logo más pequeño */
        height: auto; /* Alto ajustado automáticamente */
        margin-left: 10px; /* Espacio a la izquierda del logo */
    }
            </style>
              
                
        </head>
        <body>


          <div class="navbar">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIfw6sh1BkF1XQkPPnIcTsnLPvNqXtGe0hjRZj_K_wr1u9qxFYbDtIKycrFz_MeERwfMI&usqp=CAU" alt="" width="60" height="42" class="d-inline-block align-text-top">
                    Bienvenido Administrador
                    
                    <a href="{{ url_for('main.logout') }}" class="volver-button">salir</a>
                  </div>
                  <div class="row" style="max-width: 80rem; margin-top: 12%;margin-bottom: 5%; margin-left: 15%;margin-right: 5%;">
  <div class="col-sm-6" >
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Optometras</h5>
        <p class="card-text">Da click para consultar optometras disponibles y registrar</p>
        <a href="{{ url_for('admin.optometras') }}" class="btn btn-primary">Optometras</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Pacientes Registrado</h5>
        <p class="card-text">Da click para consultar pacientes que han sido registrados</p>
        <a href="{{ url_for('admin.pacientes') }}" class="btn btn-primary">Pacientes registrados</a>
      </div>
    </div>
  </div>
</div>
<div class="row" style="max-width: 80rem; margin-top: 5%;margin-bottom: 5%; margin-left: 15%;margin-right: 5%;">
  <div class="col-sm-6" >
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Inventario</h5>
        <p class="card-text">Da click para consultar inventario</p>
        <a href="{{ url_for('admin.inventario') }}" class="btn btn-primary">Inventario</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Citas</h5>
        <p class="card-text">Da click para consultar Citas</p>
        <a href="{{ url_for('admin.eleccion_citas') }}" class="btn btn-primary">Citas</a>
      </div>
    </div>
  </div>
</div>
<div class="row" style="max-width: 80rem; margin-top: 5%;margin-bottom: 5%; margin-left: 15%;margin-right: 5%;">
  <div class="col-sm-6" >
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Agendas</h5>
        <p class="card-text">Da click para consultar agendas</p>
        <a href="{{ url_for('admin.agendas') }}" class="btn btn-primary">Agendas</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Ventas</h5>
        <p class="card-text">Da click para consultar Ventas</p>
        <a href="" class="btn btn-primary">Ventas</a>
      </div>
    </div>
  </div>
</div>
              <footer style="padding-top: 4%;  background: linear-gradient(to right, #2165BF, #4CD73B); ">

                <div>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-google"></i>
                  </a>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-instagram"></i>
                  </a>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-linkedin"></i>
                  </a>
                  <a href="" class="me-4 link-grayish">
                    <i class="fab fa-github"></i>
                  </a>
                </div>
               
              </section>
            
              <section class="">
                <div class="container text-center text-md-start mt-5">
                  
                  <div class="row mt-3">
                    
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                      
                      <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3 text-grayish"></i>Opticas 20/20
                      </h6>
                      <p>
                       Empresa con animo de lucro, prestadora de servicios de salud visual
                      </p>
                    </div>
             
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              
                      <h6 class="text-uppercase fw-bold mb-4">
                        Productos
                      </h6>
                      <p>
                        <a href="#!" class="text-reset">Angular</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">React</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">Vue</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">Laravel</a>
                      </p>
                    </div>
                
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                      
                      <h6 class="text-uppercase fw-bold mb-4">
                        Enlaces
                      </h6>
                      <p>
                        <a href="#!" class="text-reset">Precios</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">Ajustes</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">Pedidos</a>
                      </p>
                      <p>
                        <a href="#!" class="text-reset">Ayuda</a>
                      </p>
                    </div>
  
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            
                      <h6 class="text-uppercase fw-bold mb-4">Contacto</h6>
                      <p><i class="fas fa-home me-3 text-grayish"></i> Bogota, BG 10012, COL</p>
                      <p>
                        <i class="fas fa-envelope me-3 text-grayish"></i>
                        Mesasanti818@gmailcom
                      </p>
                      <p><i class="fas fa-phone me-3 text-grayish"></i> + 57 315 641 5028</p>
                      <p><i class="fas fa-print me-3 text-grayish"></i> + 57 311 848 2370</p>
                    </div>
                  </div>
              
                </div>
              </section>
            
              <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
                © 2022 Copyright:
                <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Santiago Mesa</a>
              </div>
            </footer>
        </body>
</html>

templates/login.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>INICIAR SESION</title>
        <link rel="stylesheet" href="../static/css/login.css">
    </head>
    <body>
        




        <form class="form" method="POST" action="{{ url_for('main.login') }}">
            <div class="box_1">
                <img src="../static/img/logo_Form.png" alt="Logo de la pagina" width="100px">
            </div>
            <label>Usuario</label>
            <input class="controls"  type="email" name="username" value="" >
            <label>Contraseña</label>
            <input class="controls" type="password" name="password" value="" >
            <button type="submit" class="button">Ingresar</button>
            <a href="index.html"><input class="button" type="submit" name="Volver al inicio" value="Volver al inicio"></a>
        </form>

        <footer>
            <div class="container">
                <div class="footer-content">
                    
                    <div class="contact-info">
                        <h4>Contacto</h4>
                        <p>Dirección: Cra. 126a #138-29, Bogotá</p>
                        <p>Teléfono: 3152595833</p>
                    </div>
                    <div class="social-media">
                        <h4>Síguenos en las Redes Sociales</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/opticasvision2020colombia/"><img src="img/facebook-icon.png" alt="Facebook"></a></li>
                            
                            <li><a href="https://www.instagram.com/opticas.2020/"><img src="img/instagram-icon.png" alt="Instagram"></a></li>
                        </ul>
                    </div>
                    
                </div>
                <div class="Copyright">
                    <p>Copyright@ 2023 Derechos Reservados</p>
                </div>
            </div>
        </footer>
        
    </body>
</html>

templates/optometras.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Optometras</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Agrega tus enlaces CSS personalizados aquí -->
    <style>
        /* Estilos para la tabla */
        .container-table {
            text-align: center;
            margin-top: 5%;
        }

        /* Estilos para los botones de modificar y eliminar */
        .btn-modificar {
            background-color: #2165BF; /* Color azul */
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 5px; /* Espacio a la derecha del botón */
        }

        .btn-eliminar {
            background-color: #FF0000; /* Color rojo */
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-modificar:hover, .btn-eliminar:hover {
            background-color: #3b3ed7; /* Cambio de color al hacer hover */
        }

        /* Estilos para el navbar */
        .navbar {
            background: linear-gradient(to right, #2165BF, #4CD73B); /* Combinación de colores azul y verde */
            color: white;
            padding: 15px 30px; /* Aumentar el espacio vertical y horizontal */
            display: flex;
            justify-content: space-between; /* Mover el logo y el botón a los lados */
            align-items: center; /* Centrar verticalmente */
        }

        /* Estilos para el botón "Salir" */
        .volver-button {
background-color: #2165BF; /* Color azul */
color: white;
border: none;
padding: 10px 20px;
border-radius: 5px;
cursor: pointer;
margin-right: -30%; /* Espacio a la derecha del botón */
}
.volver-button2 {
background-color: #2165BF; /* Color azul */
color: white;
border: none;
padding: 10px 20px;
border-radius: 5px;
cursor: pointer;
margin-right: 5px; /* Espacio a la derecha del botón */
}

        .volver-button:hover {
            background-color: #5660e9; /* Cambio a verde al hacer hover */
            text-decoration: none;
        }

        /* Estilos para el logo */
        .logo {
            width: 10px; /* Ancho del logo más pequeño */
            height: auto; /* Alto ajustado automáticamente */
            margin-left: 10px; /* Espacio a la izquierda del logo */
        }

        /* Estilos para el footer */
        footer {
            padding-top: 4%;
            background: linear-gradient(to right, #2165BF, #4CD73B);
            margin-top: 10%;
        }

        .link-grayish {
            color: #d3d3d3; /* Color gris para los íconos de redes sociales */
            margin-right: 10px; /* Espacio entre los íconos */
        }

        /* Estilo para el botón "Registrar Nuevo" */
        .btn-registrar-nuevo {
            background-color: #006391; /* Color verde */
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-bottom: 5%;
        }

        .btn-registrar-nuevo:hover {
            background-color: #2165BF; /* Cambio a azul al hacer hover */
        }
    </style>
</head>
<body>
   <!-- Navbar -->
<div class="navbar">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIfw6sh1BkF1XQkPPnIcTsnLPvNqXtGe0hjRZj_K_wr1u9qxFYbDtIKycrFz_MeERwfMI&usqp=CAU" alt="" width="60" height="42" class="d-inline-block align-text-top">
    Bienvenido Administrador
    <a href="{{ url_for('main.logout') }}" class="volver-button">Salir</a>
    <a href="{{ url_for('main.dashboard') }}" class="volver-button2">volver</a>

</div>

    <!-- Contenedor principal -->
    <div class="container container-table">
        <h1>Optometras Disponibles</h1>
        <a href="{{ url_for('admin.registro_doctor') }}" class="btn btn-registrar-nuevo">Registrar Nuevo</a> <!-- Botón "Registrar Nuevo" -->
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Edad</th>
                    <th>Teléfono</th>
                    <th>Número de Documento</th>
                    <th>Tipo de Documento</th>
                    <th>Email</th>
                    <th>Dirección</th>
                    <th>Rol</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                {% for optometra in optometras %}
                    <tr>
                        <td>{{ optometra.id_u }}</td>
                        <td>{{ optometra.nombre }}</td>
                        <td>{{ optometra.apellidos }}</td>
                        <td>{{ optometra.edad }}</td>
                        <td>{{ optometra.tel }}</td>
                        <td>{{ optometra.n_documento }}</td>
                        <td>{{ optometra.t_Documento }}</td>
                        <td>{{ optometra.email }}</td>
                        <td>{{ optometra.dirrecion }}</td>
                        <td>{{ optometra.rol }}</td>
                        <td>{{ optometra.estado_u }}</td>
                        <td>
                            <a href="{{ url_for('admin.editar_doctor', id=optometra.id_u) }}" class="btn btn-modificar">Modificar</a>
                            <form method="POST" action="{{ url_for('admin.eliminar_doctor', id=optometra.id_u) }}" style="display: inline;">
                                <button type="submit" class="btn btn-eliminar">Eliminar</button>
                            </form>                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Agrega tus enlaces a scripts JS aquí -->

</body>
</html>